USE [master]
GO

/****** Object:  Database [ExcelExporting]    Script Date: 6/9/2018 4:18:34 AM ******/
CREATE DATABASE [ExcelExporting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExcelExporting', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ExcelExporting.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ExcelExporting_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ExcelExporting_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ExcelExporting] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExcelExporting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExcelExporting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExcelExporting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExcelExporting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExcelExporting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExcelExporting] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExcelExporting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ExcelExporting] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ExcelExporting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExcelExporting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExcelExporting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExcelExporting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExcelExporting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExcelExporting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExcelExporting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExcelExporting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExcelExporting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ExcelExporting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExcelExporting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExcelExporting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExcelExporting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExcelExporting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExcelExporting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExcelExporting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExcelExporting] SET RECOVERY FULL 
GO

ALTER DATABASE [ExcelExporting] SET  MULTI_USER 
GO

ALTER DATABASE [ExcelExporting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExcelExporting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExcelExporting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExcelExporting] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ExcelExporting] SET  READ_WRITE 
GO


